repos:
- repo: local
  hooks:
  - id: lint
    name: Lint Python code
    language: system
    entry: make lint
    
  - id: typecheck
    name: Type check Python code
    language: system
    entry: make type-check

  - id: docs
    name: Autogenerate rules documentation
    language: system
    entry: make docs
